"""_summary_"""
tupla = ("antoni", "antonio", "andrew", "alexis", "andrea","andrea")
print("las tuplas son inmutables por lo que no se pueden modificar una vez declaradas.")
print("________________________________________________________________")
print("tupla [:] -> acceder a toda la tupla ")
print(tupla[:])
print("________________________________________________________________")
print("tupla[2:4] -> accede a los indices entre 2 y 4")
print(tupla[2:4])
print("________________________________________________________________")
print("tupla[2] -> accede al indice 2 o el que se le indique ")
print(tupla[2])
print("________________________________________________________________")
print("tupla.index ->ver en que posicion se encuentra un elemento que se pase como parametro")
print(tupla.index("antoni"))
print("________________________________________________________________")
print("tupla.count(andrea) -> cuenta cuantas veces se repite un elemento")
print(tupla[:])
print(tupla.count("andrea"))
